# Generated by Django 2.2.2 on 2022-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='further_study',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='prayer',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='devotional',
            name='scripture',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
