# Generated by Django 2.2.2 on 2022-07-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220713_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='devotional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devotional_img'),
        ),
    ]
